app:
  developer:
    name: Syed Ali Abbas Raza


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password:

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect